# Generated by Django 2.2 on 2021-06-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dbhomehref'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('remark', models.CharField(max_length=1000, null=True)),
                ('user', models.CharField(max_length=15, null=True)),
                ('other_user', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
